openapi: "3.1.0"
info:
  title: dingo
  description: Broadcast composing service 🧼
paths:
  /ping:
    get:
      summary: Ping
      description: Do nothing.
      tags:
        - Ping
      responses:
        "204":
          description: Request fulfilled, nothing follows
          headers:
            Cache-Control:
              schema:
                type: string
                example: no-cache
  /playlist:
    get:
      summary: Get playlist
      description: Get the current playlist.
      tags:
        - Playlist
      responses:
        "200":
          description: Request fulfilled, document follows
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetPlaylistResponse"
        "404":
          description: Request failed, resource not found
          content:
            text/plain:
              schema:
                type: string
                example: No playlist is currently set.
    put:
      summary: Update playlist
      description: Update the current playlist.
      tags:
        - Playlist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutPlaylistRequest"
      responses:
        "200":
          description: Request fulfilled, document follows
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutPlaylistResponse"
        "400":
          description: Request failed, bad request
          content:
            text/plain:
              schema:
                type: string
                example: Request body is not a valid JSON object.
    delete:
      summary: Remove playlist
      description: Remove the current playlist.
      tags:
        - Playlist
      responses:
        "204":
          description: Request fulfilled, nothing follows
components:
  schemas:
    GetPlaylistResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 8be4df61-93ca-11d2-aa0d-00e098032b8c
      required:
        - id
    PutPlaylistRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 8be4df61-93ca-11d2-aa0d-00e098032b8c
      required:
        - id
    PutPlaylistResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: 8be4df61-93ca-11d2-aa0d-00e098032b8c
      required:
        - id
